name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    if: ${{ github.repository_owner == 'jenkinsci' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v6
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
