# Automates creation of Release Drafts using Release Drafter
# More Info: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    # Only draft release notes on the repo in the jenkinsci GitHub organization
    if: ${{ github.repository_owner == 'jenkinsci' }}
    runs-on: ubuntu-latest
    steps:
      # https://github.com/release-drafter/release-drafter/issues/871#issuecomment-3686135188
      - name: Wait for 15 seconds to ensure GraphQL consistency
        shell: bash
        run: sleep 15s
      # Drafts your next Release notes as Pull Requests are merged into the default branch
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
